### ISSUE TITLE
Validation for have breadcrumbs

### ISSUE THREAD

**Issue by JulioGa1011** [CCEO/vue-index-table#13]
I will like indicate if i would like or no the breadcrumbs above the page, because some times we have another sections between breadcrumbs and table.

**Comment by luisalcarasr** [comment]
Example of breadcumbs definition in the future:
```js
breadcrumbs: [
  {
    type: "icon",
    content: "home",
    url: "/home"
  },
  {
    type: "text",
    content: "Users",
    url: "http://example.io/users",
  },
  {
    type: "text",
    content: "New",
  }
[
```
If you don't define the breadcrumbs properity so not show it.
